### PR TITLE
Major UI update, translations, trailer workaround

### PR DESCRIPTION
**Pull request by direc85**
Hi,

First I checked the trailer player situation, and decided to make it open in a browser instead, since that works surprisingly well. Then I ended up fixing and improving a ton of smaller and larger UI issues and ended up pretty much going through large amount of QML code base. I also replaced the placeholder and play symbol images with Jolla theme ones, and removed a lot of dead code, resulting in even smaller RPM package!

The result is a lot cleaner UI that responds better to different devices with different font sizes selected.

I also made the application translatable and did Finnish translation myself. The country and language page gave me a serious headache, and in the end it turned out Qt doesn't provide every country and language name in every other languge, so I simply ended up constructing the necessary strings myself and translating them by hand. It's trivial to add more languages and countries later, if needed.

 No need to confess that I got nerd sniped pretty hard on this, but I'm very pleased with the outcome. Please consider advertising translations on the Store page, so that Estonians, Latvians and Lithuanians can also enjoy the application in their native languages, once it gets translated!

Thanks!

### CODE REVIEW

**Comment by skvark** [comment]
Thanks, I'll go through this probably during next week. There were indeed many issues on the UI side and I'm happy you took the time to fix them :)

**Comment by skvark** [comment]
Looks good. One question though, why is the active tab indicator height different between "In Theatres" and "Coming Soon"?

sailkino_in_theatres
sailkino_coming_soon

I think it would be better if the heights were same on both tabs.

**Comment by direc85** [comment]
Correct; the heights should be the same. Fix committed.

I also accidentally reverted my changes to About.qml, so I pushed them again. You might want to see if the changes I made are OK to you.

**Comment by skvark** [comment]
Looks ok now. Thanks!

**Comment by skvark** [comment]
New version is now in the Harbour queue.

**Pull request merged**
